//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5466
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.WCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService.IWCFServices")]
    public interface IWCFServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServices/AddTicket", ReplyAction="http://tempuri.org/IWCFServices/AddTicketResponse")]
        void AddTicket(int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServices/BuyTickets", ReplyAction="http://tempuri.org/IWCFServices/BuyTicketsResponse")]
        int BuyTickets(int Num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServices/GetRemainingNum", ReplyAction="http://tempuri.org/IWCFServices/GetRemainingNumResponse")]
        int GetRemainingNum();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IWCFServicesChannel : Client.WCFService.IWCFServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFServicesClient : System.ServiceModel.ClientBase<Client.WCFService.IWCFServices>, Client.WCFService.IWCFServices {
        
        public WCFServicesClient() {
        }
        
        public WCFServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddTicket(int count) {
            base.Channel.AddTicket(count);
        }
        
        public int BuyTickets(int Num) {
            return base.Channel.BuyTickets(Num);
        }
        
        public int GetRemainingNum() {
            return base.Channel.GetRemainingNum();
        }
    }
}
