//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5466
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// 原始文件名:
// 生成日期: 2013-12-26 11:53:15
namespace FsEmployeeYuan
{
    
    /// <summary>
    /// 架构中不存在 SqliteTest 的注释。
    /// </summary>
    public partial class SqliteTest : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// 请使用应用程序配置文件的“SqliteTest”部分中的连接字符串初始化新 SqliteTest 对象。
        /// </summary>
        public SqliteTest() : 
                base("name=SqliteTest", "SqliteTest")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 SqliteTest 对象。
        /// </summary>
        public SqliteTest(string connectionString) : 
                base(connectionString, "SqliteTest")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 SqliteTest 对象。
        /// </summary>
        public SqliteTest(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "SqliteTest")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// 架构中不存在 Table1 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Table1> Table1
        {
            get
            {
                if ((this._Table1 == null))
                {
                    this._Table1 = base.CreateQuery<Table1>("[Table1]");
                }
                return this._Table1;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Table1> _Table1;
        /// <summary>
        /// 架构中不存在 Table1 的注释。
        /// </summary>
        public void AddToTable1(Table1 table1)
        {
            base.AddObject("Table1", table1);
        }
    }
    /// <summary>
    /// 架构中不存在 TestModel.Table1 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TestModel", Name="Table1")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Table1 : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Table1 对象。
        /// </summary>
        /// <param name="id">ID 的初始值。</param>
        public static Table1 CreateTable1(int id)
        {
            Table1 table1 = new Table1();
            table1.ID = id;
            return table1;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 C1 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string C1
        {
            get
            {
                return this._C1;
            }
            set
            {
                this.OnC1Changing(value);
                this.ReportPropertyChanging("C1");
                this._C1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("C1");
                this.OnC1Changed();
            }
        }
        private string _C1;
        partial void OnC1Changing(string value);
        partial void OnC1Changed();
    }
}
