//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5466
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("EmployeeYuanModel", "FK_订单Detail_订单", "订单", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(FsEmployeeYuan.订单), "订单Detail", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FsEmployeeYuan.订单Detail))]

// 原始文件名:
// 生成日期: 2013-12-20 11:58:30
namespace FsEmployeeYuan
{
    
    /// <summary>
    /// 架构中不存在 Entities 的注释。
    /// </summary>
    public partial class Entities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// 请使用应用程序配置文件的“Entities”部分中的连接字符串初始化新 Entities 对象。
        /// </summary>
        public Entities() : 
                base("name=Entities", "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 Entities 对象。
        /// </summary>
        public Entities(string connectionString) : 
                base(connectionString, "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 Entities 对象。
        /// </summary>
        public Entities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "Entities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// 架构中不存在 订单 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<订单> 订单
        {
            get
            {
                if ((this._订单 == null))
                {
                    this._订单 = base.CreateQuery<订单>("[订单]");
                }
                return this._订单;
            }
        }
        private global::System.Data.Objects.ObjectQuery<订单> _订单;
        /// <summary>
        /// 架构中不存在 订单Detail 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<订单Detail> 订单Detail
        {
            get
            {
                if ((this._订单Detail == null))
                {
                    this._订单Detail = base.CreateQuery<订单Detail>("[订单Detail]");
                }
                return this._订单Detail;
            }
        }
        private global::System.Data.Objects.ObjectQuery<订单Detail> _订单Detail;
        /// <summary>
        /// 架构中不存在 物料资料 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<物料资料> 物料资料
        {
            get
            {
                if ((this._物料资料 == null))
                {
                    this._物料资料 = base.CreateQuery<物料资料>("[物料资料]");
                }
                return this._物料资料;
            }
        }
        private global::System.Data.Objects.ObjectQuery<物料资料> _物料资料;
        /// <summary>
        /// 架构中不存在 订单 的注释。
        /// </summary>
        public void AddTo订单(订单 订单)
        {
            base.AddObject("订单", 订单);
        }
        /// <summary>
        /// 架构中不存在 订单Detail 的注释。
        /// </summary>
        public void AddTo订单Detail(订单Detail 订单Detail)
        {
            base.AddObject("订单Detail", 订单Detail);
        }
        /// <summary>
        /// 架构中不存在 物料资料 的注释。
        /// </summary>
        public void AddTo物料资料(物料资料 物料资料)
        {
            base.AddObject("物料资料", 物料资料);
        }
    }
    /// <summary>
    /// 架构中不存在 EmployeeYuanModel.订单 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="EmployeeYuanModel", Name="订单")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class 订单 : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 订单 对象。
        /// </summary>
        /// <param name="id">ID 的初始值。</param>
        public static 订单 Create订单(int id)
        {
            订单 订单 = new 订单();
            订单.ID = id;
            return 订单;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 订单号 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string 订单号
        {
            get
            {
                return this._订单号;
            }
            set
            {
                this.On订单号Changing(value);
                this.ReportPropertyChanging("订单号");
                this._订单号 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("订单号");
                this.On订单号Changed();
            }
        }
        private string _订单号;
        partial void On订单号Changing(string value);
        partial void On订单号Changed();
        /// <summary>
        /// 架构中不存在 订单Detail 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EmployeeYuanModel", "FK_订单Detail_订单", "订单Detail")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<订单Detail> 订单Detail
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<订单Detail>("EmployeeYuanModel.FK_订单Detail_订单", "订单Detail");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<订单Detail>("EmployeeYuanModel.FK_订单Detail_订单", "订单Detail", value);
                }
            }
        }
    }
    /// <summary>
    /// 架构中不存在 EmployeeYuanModel.订单Detail 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="EmployeeYuanModel", Name="订单Detail")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class 订单Detail : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 订单Detail 对象。
        /// </summary>
        /// <param name="id">ID 的初始值。</param>
        public static 订单Detail Create订单Detail(int id)
        {
            订单Detail 订单Detail = new 订单Detail();
            订单Detail.ID = id;
            return 订单Detail;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 单号 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string 单号
        {
            get
            {
                return this._单号;
            }
            set
            {
                this.On单号Changing(value);
                this.ReportPropertyChanging("单号");
                this._单号 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("单号");
                this.On单号Changed();
            }
        }
        private string _单号;
        partial void On单号Changing(string value);
        partial void On单号Changed();
        /// <summary>
        /// 架构中不存在属性 物料编号 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string 物料编号
        {
            get
            {
                return this._物料编号;
            }
            set
            {
                this.On物料编号Changing(value);
                this.ReportPropertyChanging("物料编号");
                this._物料编号 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("物料编号");
                this.On物料编号Changed();
            }
        }
        private string _物料编号;
        partial void On物料编号Changing(string value);
        partial void On物料编号Changed();
        /// <summary>
        /// 架构中不存在属性 物料名称 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string 物料名称
        {
            get
            {
                return this._物料名称;
            }
            set
            {
                this.On物料名称Changing(value);
                this.ReportPropertyChanging("物料名称");
                this._物料名称 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("物料名称");
                this.On物料名称Changed();
            }
        }
        private string _物料名称;
        partial void On物料名称Changing(string value);
        partial void On物料名称Changed();
        /// <summary>
        /// 架构中不存在属性 单位 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string 单位
        {
            get
            {
                return this._单位;
            }
            set
            {
                this.On单位Changing(value);
                this.ReportPropertyChanging("单位");
                this._单位 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("单位");
                this.On单位Changed();
            }
        }
        private string _单位;
        partial void On单位Changing(string value);
        partial void On单位Changed();
        /// <summary>
        /// 架构中不存在属性 数量 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> 数量
        {
            get
            {
                return this._数量;
            }
            set
            {
                this.On数量Changing(value);
                this.ReportPropertyChanging("数量");
                this._数量 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("数量");
                this.On数量Changed();
            }
        }
        private global::System.Nullable<int> _数量;
        partial void On数量Changing(global::System.Nullable<int> value);
        partial void On数量Changed();
        /// <summary>
        /// 架构中不存在属性 单价 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> 单价
        {
            get
            {
                return this._单价;
            }
            set
            {
                this.On单价Changing(value);
                this.ReportPropertyChanging("单价");
                this._单价 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("单价");
                this.On单价Changed();
            }
        }
        private global::System.Nullable<decimal> _单价;
        partial void On单价Changing(global::System.Nullable<decimal> value);
        partial void On单价Changed();
        /// <summary>
        /// 架构中不存在属性 金额 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> 金额
        {
            get
            {
                return this._金额;
            }
            set
            {
                this.On金额Changing(value);
                this.ReportPropertyChanging("金额");
                this._金额 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("金额");
                this.On金额Changed();
            }
        }
        private global::System.Nullable<decimal> _金额;
        partial void On金额Changing(global::System.Nullable<decimal> value);
        partial void On金额Changed();
        /// <summary>
        /// 架构中不存在属性 备注 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string 备注
        {
            get
            {
                return this._备注;
            }
            set
            {
                this.On备注Changing(value);
                this.ReportPropertyChanging("备注");
                this._备注 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("备注");
                this.On备注Changed();
            }
        }
        private string _备注;
        partial void On备注Changing(string value);
        partial void On备注Changed();
        /// <summary>
        /// 架构中不存在 订单 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EmployeeYuanModel", "FK_订单Detail_订单", "订单")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public 订单 订单
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<订单>("EmployeeYuanModel.FK_订单Detail_订单", "订单").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<订单>("EmployeeYuanModel.FK_订单Detail_订单", "订单").Value = value;
            }
        }
        /// <summary>
        /// 架构中不存在 订单 的注释。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<订单> 订单Reference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<订单>("EmployeeYuanModel.FK_订单Detail_订单", "订单");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<订单>("EmployeeYuanModel.FK_订单Detail_订单", "订单", value);
                }
            }
        }
    }
    /// <summary>
    /// 架构中不存在 EmployeeYuanModel.物料资料 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="EmployeeYuanModel", Name="物料资料")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class 物料资料 : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 物料资料 对象。
        /// </summary>
        /// <param name="id">ID 的初始值。</param>
        public static 物料资料 Create物料资料(int id)
        {
            物料资料 物料资料 = new 物料资料();
            物料资料.ID = id;
            return 物料资料;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 物料编号 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string 物料编号
        {
            get
            {
                return this._物料编号;
            }
            set
            {
                this.On物料编号Changing(value);
                this.ReportPropertyChanging("物料编号");
                this._物料编号 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("物料编号");
                this.On物料编号Changed();
            }
        }
        private string _物料编号;
        partial void On物料编号Changing(string value);
        partial void On物料编号Changed();
        /// <summary>
        /// 架构中不存在属性 物料名称 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string 物料名称
        {
            get
            {
                return this._物料名称;
            }
            set
            {
                this.On物料名称Changing(value);
                this.ReportPropertyChanging("物料名称");
                this._物料名称 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("物料名称");
                this.On物料名称Changed();
            }
        }
        private string _物料名称;
        partial void On物料名称Changing(string value);
        partial void On物料名称Changed();
        /// <summary>
        /// 架构中不存在属性 单位 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string 单位
        {
            get
            {
                return this._单位;
            }
            set
            {
                this.On单位Changing(value);
                this.ReportPropertyChanging("单位");
                this._单位 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("单位");
                this.On单位Changed();
            }
        }
        private string _单位;
        partial void On单位Changing(string value);
        partial void On单位Changed();
    }
}
